const productos = [{
    id: 1,
    foto: '../img/MusculosaGrisShark.jpg',
    nombre: "musculosa gris shark",
    precio: 4000,
    categoria: "musculosas",
    cantidad: 1,
},
{
    id: 2,
    foto: '../img/MusculosaBlancaEntallada.jpg',
    nombre: "musculosa blanca entallada",
    precio: 4000,
    categoria: "musculosas",
    cantidad: 1,
},
{
    id: 3,
    foto: "../img/MusculosaRojaAbiertaBasica.jpg",
    nombre: "musculosa roja abierta basica",
    precio: 40000,
    categoria: "musculosas",
    cantidad: 1,
},
{
    id: 4,
    foto: '../img/RemeraNegra.jpg',
    nombre: "remera negra",
    precio: 4500,
    categoria: "remeras",
    cantidad: 1,
},
{
    id: 5,
    foto: '../img/RemeraBlanca.jpg',
    nombre: "remera blanca",
    precio: 4500,
    categoria: "remeras",
    cantidad: 1,
},
{
    id: 6,
    foto: "../img/RemeraOversizeAzul.jpg",
    nombre: "remera oversize azul",
    precio: 4500,
    categoria: "remeras",
    cantidad: 1,
},
{
    id: 7,
    foto: '../img/creatina.jpg',
    nombre: "creatina",
    precio: 11500,
    categoria: "suplementosstar",
    cantidad: 1,
},
{
    id: 8,
    foto: '../img/proteina2lbs.jpg',
    nombre: "proteina 2 lbs",
    precio: 6200,
    categoria: "suplementosstar",
    cantidad: 1,
},
{
    id: 9,
    foto: '../img/mutant-mass.jpg',
    nombre: "Mutant mass 1.5kg",
    precio: 6300,
    categoria: "suplementosstar",
    cantidad: 1,
},
];